#!/usr/bin/env python3
"""
Figure 5a/5b Style Graph from hit_ratio_analysis_*.csv
Reads the CSV file generated by main.py and creates 3-tier graphs.
"""

import matplotlib.pyplot as plt
import numpy as np
import glob
import pandas as pd
from pathlib import Path
from datetime import datetime


class ComprehensiveGrapher:
    def __init__(self):
        # Algorithms expected in your CSV (will be automatically populated from data)
        self.algorithms = None
        self.zipf_values = [0.25, 0.5, 1.0, 2.0]

        # 🎨 Beautiful color palette
        self.colors = {
            'LRU': '#E74C3C',
            'Popularity': '#3498DB',
            'MAB_Original': '#9B59B6',
            'MAB_Contextual': '#2ECC71',
            'Enhanced_Federated_MAB': '#F39C12',
            'Federated_MAB': '#F39C12',      # fallback
            'Oracle': '#FFD700'
        }

        # 🎯 SYNTHETIC Oracle values (like Figure 5a/5b)
        self.oracle_performance = {
            0.25: {'UAV': 0.05, 'Vehicle': 0.06, 'BS': 0.04},
            0.5:  {'UAV': 0.08, 'Vehicle': 0.09, 'BS': 0.07},
            1.0:  {'UAV': 0.20, 'Vehicle': 0.22, 'BS': 0.18},
            2.0:  {'UAV': 0.70, 'Vehicle': 0.75, 'BS': 0.65}
        }

    def load_comprehensive_data(self):
        """Read hit_ratio_analysis_*.csv and extract per‑tier hit ratios."""
        csv_files = glob.glob("hit_ratio_analysis_*.csv")
        if not csv_files:
            print("❌ No hit_ratio_analysis_*.csv files found!")
            return None

        latest_csv = max(csv_files, key=lambda x: Path(x).stat().st_mtime)
        print(f"📂 Using CSV: {latest_csv}")

        df = pd.read_csv(latest_csv)

        # Discover which algorithms are present
        self.algorithms = sorted(df['Algorithm'].unique())
        print(f"🔍 Found algorithms: {self.algorithms}")

        # Build nested dictionary: experimental_data[alpha][algorithm] = {'UAV':..., 'Vehicle':..., 'BS':...}
        experimental_data = {}
        for alpha in self.zipf_values:
            alpha_df = df[df['Alpha'] == alpha]
            if alpha_df.empty:
                print(f"⚠️  No data for alpha = {alpha}")
                continue
            experimental_data[alpha] = {}
            for _, row in alpha_df.iterrows():
                alg = row['Algorithm']
                experimental_data[alpha][alg] = {
                    'UAV': row['uav_hit_ratio'] / 100.0,        # CSV stores percentages
                    'Vehicle': row['vehicle_hit_ratio'] / 100.0,
                    'BS': row['bs_hit_ratio'] / 100.0
                }
        return experimental_data

    def create_tier_specific_data(self, experimental_data):
        """Return a nested dict[alpha][algorithm][tier] using CSV data directly."""
        # The data is already per‑tier, so we simply pass it through.
        return experimental_data

    def create_figure_5ab_graph(self, tier_data, save_dir="./comprehensive_graphs"):
        save_path = Path(save_dir)
        save_path.mkdir(exist_ok=True)
        print(f"\n📊 Creating Figure 5a/5b style graphs...")
        print(f" 读取文件路径：{save_dir}")

        # 调小字体
        plt.style.use('default')
        plt.rcParams.update({
            'font.size': 9,
            'font.family': 'serif',
            'axes.linewidth': 1.0,
            'figure.dpi': 300,
            'axes.titlesize': 10,
            'axes.labelsize': 9,
            'xtick.labelsize': 8,
            'ytick.labelsize': 8,
            'legend.fontsize': 8,
        })

        fig, axes = plt.subplots(1, 3, figsize=(12, 4))  # 宽度12英寸，高度4英寸
        # 减小字体
        
        fig.suptitle('Cache Hit Ratio Performance - Comprehensive Results',
                    fontsize=12, fontweight='bold', y=1.02)

        tiers = ['UAV', 'Vehicle', 'BS']
        tier_titles = ['UAV Caching', 'Vehicle Caching', 'BS Caching']

        for idx, (tier, title) in enumerate(zip(tiers, tier_titles)):
            ax = axes[idx]
            zipf_labels = [str(z) for z in self.zipf_values]
            x_pos = np.arange(len(zipf_labels))
            width = 0.1  # 条宽减小

            # 绘制实验数据
            for i, algorithm in enumerate(self.algorithms):
                values = [tier_data[zipf][algorithm][tier] if zipf in tier_data and algorithm in tier_data[zipf] else 0
                        for zipf in self.zipf_values]
                bar_pos = x_pos + (i - len(self.algorithms)//2) * width
                bars = ax.bar(bar_pos, values, width,
                            label=algorithm, color=self.colors.get(algorithm, '#888888'),
                            alpha=0.8, edgecolor='white', linewidth=0.7)
                # 添加数值标签（只对>0.01的显示，避免拥挤）
                for bar, value in zip(bars, values):
                    if value > 0.01:
                        height = bar.get_height()
                        ax.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                                f'{value:.2f}', ha='center', va='bottom', fontsize=7, fontweight='bold')

            # 绘制 Oracle（理论最优）
            oracle_values = [self.oracle_performance[zipf][tier] for zipf in self.zipf_values]
            oracle_pos = x_pos + (len(self.algorithms)//2) * width + width
            oracle_bars = ax.bar(oracle_pos, oracle_values, width,
                                label='Oracle', color=self.colors['Oracle'],
                                alpha=0.8, edgecolor='white', linewidth=0.7)
            for bar, value in zip(oracle_bars, oracle_values):
                height = bar.get_height()
                ax.text(bar.get_x() + bar.get_width()/2., height + 0.01,
                        f'{value:.2f}', ha='center', va='bottom', fontsize=7, fontweight='bold')

            ax.set_title(title, fontsize=10, fontweight='bold')
            ax.set_xlabel('Zipf Parameter (α)', fontsize=9)
            ax.set_ylabel('Cache Hit Ratio' if idx==0 else '', fontsize=9)
            ax.set_xticks(x_pos)
            ax.set_xticklabels(zipf_labels)
            ax.set_ylim(0, 1.0)  # 固定范围，避免波动
            ax.grid(True, alpha=0.2, axis='y', linestyle='-', linewidth=0.5)
            ax.set_axisbelow(True)

            if idx == 0:
                ax.legend(loc='upper left', bbox_to_anchor=(1.02, 1), fontsize=8, frameon=True)

        plt.tight_layout(rect=[0, 0, 1, 0.95])  # 为suptitle留空间
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        png_file = save_path / f"comprehensive_figure_5ab_{timestamp}.png"
        pdf_file = save_path / f"comprehensive_figure_5ab_{timestamp}.pdf"
        plt.savefig(png_file, dpi=300, bbox_inches='tight', pad_inches=0.05)
        plt.savefig(pdf_file, bbox_inches='tight', pad_inches=0.05)
        print(f"💾 Graphs saved: {png_file}, {pdf_file}")
        plt.show()
        plt.close()

    def print_data_summary(self, tier_data):
        """Print a summary of the data being graphed."""
        print(f"\n📈 DATA SUMMARY:")
        print("=" * 60)

        for zipf in sorted(tier_data.keys()):
            print(f"\nZipf α = {zipf}:")
            for tier in ['UAV', 'Vehicle', 'BS']:
                print(f"  {tier}:")
                sorted_algs = sorted(
                    tier_data[zipf].items(),
                    key=lambda x: x[1][tier], reverse=True
                )
                for alg, performance in sorted_algs:
                    print(f"    {alg:<25}: {performance[tier]:.4f}")

    def run_analysis(self):
        """Run the complete analysis."""
        print("🚀 COMPREHENSIVE RESULTS → Figure 5a/5b Style Graphs")
        print("=" * 60)

        experimental_data = self.load_comprehensive_data()
        if experimental_data is None:
            print("❌ Could not load comprehensive data!")
            return

        tier_data = self.create_tier_specific_data(experimental_data)
        self.print_data_summary(tier_data)
        self.create_figure_5ab_graph(tier_data)

        print("\n✅ Analysis Complete!")
        print("📊 Created Figure 5a/5b style graphs using:")
        print("   • Algorithm data: YOUR comprehensive experimental results")
        print("   • Oracle data: Synthetic baselines for comparison")
        print("   • Tier data: Direct from CSV (UAV/Vehicle/BS hit ratios)")


def main():
    print("🎯 Comprehensive Results → Figure 5a/5b Graphs")
    print("=" * 50)
    grapher = ComprehensiveGrapher()
    grapher.run_analysis()
    print("\n🎉 Done! Your comprehensive results are now in Figure 5a/5b format!")


if __name__ == "__main__":
    main()